prometheus:
  additionalPodMonitors:
    - name: api-gateway-pod-monitor
      selector:
        matchLabels:
          app: qna-apigateway-pod
      podMetricsEndpoints:
        - port: "8080"
          path: "/actuator/prometheus"
  additionalServiceMonitors:
    - name: api-gateway-service-monitor
      selector:
        matchLabels:
          app: qna-api-gateway-service
      endpoints:
        - port: "8080"
          path: "/actuator/prometheus"
      
      

  service:
    type: NodePort
    nodePort: 30090    
kubeDns:
  enabled: true
coreDns:
  enabled: false
grafana:
  service:
    type: NodePort
    nodePort: 30020
