prometheus:
  additionalPodMonitors:
    - name: api-gateway-pod-monitor
      selector:
        app: qna-apigateway-pod
      podMetricsEndpoints:
        port: 8080
        path: /actuator/prometheus
kubeDns:
  enabled: true
grafana:
  service:
    type: NodePort
    nodePort: 30020
